import { Room, RatePlan, Reservation } from '@/types';

export const MOCK_RATE_PLANS: RatePlan[] = [
  {
    id: 'standard',
    name: 'flex rate (free cancellation)',
    description: 'cancel up to 48 hours before check-in with zero fee. breakfast optional.',
    priceMultiplier: 1.0,
    includedBenefits: ['free high-speed Wi-Fi', 'welcome drink on arrival', 'flexible cancellation'],
  },
  {
    id: 'breakfast',
    name: 'daily gourmet breakfast included',
    description: 'enjoy daily morning buffet & à la carte breakfast at our oceanfront bistro.',
    priceMultiplier: 1.15,
    includedBenefits: ['daily breakfast for all guests', 'free high-speed Wi-Fi', 'welcome fruit basket & prosecco'],
  },
  {
    id: 'full-experience',
    name: 'tantor luxury experience package',
    description: 'includes breakfast, 3-course dinner, daily spa credit, and airport transfer.',
    priceMultiplier: 1.4,
    includedBenefits: [
      'daily breakfast & 3-course chef dinner',
      '$100 daily spa credit',
      'complimentary roundtrip airport transfer',
      'sunset cocktail hour daily',
    ],
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-1',
    slug: 'grand-ocean-villa',
    name: 'Grand Ocean Villa',
    shortDescription: 'panoramic sea views with private infinity plunge pool and spacious teak deck.',
    description:
      'Perched directly over the azure coastline, the Grand Ocean Villa offers uncompromised solitude and breath-taking sunset vistas. Featuring a master bedroom with king bed, open-plan living sanctuary, private plunge pool, and indoor/outdoor rain shower.',
    maxOccupancy: 3,
    sizeSqm: 120,
    bedType: '1 King Bed',
    view: 'Unobstructed Ocean View',
    basePrice: 480,
    featured: true,
    photos: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Private plunge pool',
      'Ocean view terrace',
      'Outdoor rain shower',
      'Personal butler service',
      'Espresso bar & wine cellar',
      'Complimentary Wi-Fi',
      '55" Smart OLED TV',
      'King Koil plush mattress',
    ],
  },
  {
    id: 'room-2',
    slug: 'palm-garden-suite',
    name: 'Palm Garden Suite',
    shortDescription: 'serene sanctuary tucked inside tropical flora with private courtyard garden.',
    description:
      'Immerse yourself in lush greenery. The Palm Garden Suite combines organic timber finishes with airy modern design. Features a private enclosed garden patio with deep soaking stone bathtub and daybed.',
    maxOccupancy: 2,
    sizeSqm: 85,
    bedType: '1 King Bed',
    view: 'Lush Botanical Garden',
    basePrice: 320,
    featured: true,
    photos: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Private garden courtyard',
      'Freestanding stone bathtub',
      'Lounge daybed',
      'Organic herbal teas & espresso',
      'Botanical bath amenities',
      'Complimentary Wi-Fi',
      'Bluetooth sound system',
    ],
  },
  {
    id: 'room-3',
    slug: 'beachfront-chalet',
    name: 'Beachfront Chalet',
    shortDescription: 'steps from soft white sands with private beach loungers and ocean breeze.',
    description:
      'Step straight from your private wooden deck onto soft ivory sand. The Beachfront Chalet is built for ocean lovers, offering floor-to-ceiling glass doors, hand-carved teak furnishings, and personal sun loungers.',
    maxOccupancy: 4,
    sizeSqm: 110,
    bedType: '1 King Bed + 1 Queen Sofabed',
    view: 'Direct Beachfront',
    basePrice: 410,
    featured: true,
    photos: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Direct beach access',
      'Dedicated sun loungers',
      'Shaded pavilion veranda',
      'Outdoor rainfall shower',
      'Mini bar refilled daily',
      'Complimentary Wi-Fi',
      'Beach bag & towel service',
    ],
  },
  {
    id: 'room-4',
    slug: 'forest-canopy-villa',
    name: 'Forest Canopy Villa',
    shortDescription: 'elevated eco-luxury villa among treetops with private infinity balcony.',
    description:
      'Suspended over the lush resort hillside, the Forest Canopy Villa delivers secluded luxury amidst singing birds and gentle mountain winds. Features a double hammock deck, glass floor viewing panel, and teak hot tub.',
    maxOccupancy: 2,
    sizeSqm: 95,
    bedType: '1 Custom King Bed',
    view: 'Mountain & Rainforest Canopy',
    basePrice: 350,
    featured: false,
    photos: [
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Treetop deck & double hammock',
      'Cedar wood hot tub',
      'Panoramic floor-to-ceiling glass',
      'Aromatherapy diffuser',
      'Telescope for stargazing',
      'Complimentary Wi-Fi',
    ],
  },
  {
    id: 'room-5',
    slug: 'royal-cliffside-penthouse',
    name: 'Royal Cliffside Penthouse',
    shortDescription: 'our flagship 2-bedroom sanctuary with 270-degree ocean views and private chef service.',
    description:
      'The crown jewel of Tantor Resort. Spanning 210 square meters over the cliffhead, this penthouse features two master suites, expansive infinity pool, private dining pavilion, and dedicated round-the-clock chef and butler.',
    maxOccupancy: 6,
    sizeSqm: 210,
    bedType: '2 King Beds + Private Lounge',
    view: '270° Panoramic Ocean & Cliffside',
    basePrice: 850,
    featured: false,
    photos: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Private 15-meter infinity pool',
      '2 master bedrooms with en-suite spa baths',
      '24/7 dedicated butler & private chef options',
      'Wine cellar & cocktail bar',
      'Private cabana & outdoor lounge',
      'Helipad transfer option',
    ],
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res-101',
    bookingCode: 'TR-84920',
    roomId: 'room-1',
    checkIn: '2026-10-10',
    checkOut: '2026-10-15',
    guests: 2,
    roomsCount: 1,
    guestName: 'Elena Rostova',
    guestPhone: '+1 555 019 2831',
    guestEmail: 'elena@example.com',
    ratePlanId: 'breakfast',
    ratePlanName: 'daily gourmet breakfast included',
    totalAmount: 2760,
    specialRequests: 'high floor preference, quiet corner if available.',
    status: 'confirmed',
    source: 'direct',
    createdAt: '2026-09-20T10:30:00Z',
  },
  {
    id: 'res-102',
    bookingCode: 'TR-19284',
    roomId: 'room-2',
    checkIn: '2026-11-01',
    checkOut: '2026-11-04',
    guests: 2,
    roomsCount: 1,
    guestName: 'Julian Vance',
    guestPhone: '+44 7700 900077',
    guestEmail: 'julian@example.com',
    ratePlanId: 'standard',
    ratePlanName: 'flex rate (free cancellation)',
    totalAmount: 960,
    specialRequests: 'honeymoon setup with fresh flowers.',
    status: 'confirmed',
    source: 'whatsapp',
    createdAt: '2026-09-24T14:15:00Z',
  },
];

export const MOCK_RESORT_INFO = {
  name: 'Tantor Resort',
  tagline: 'A secluded sanctuary deep in Habarana\'s jungle',
  address: 'Laksirigama, Anuradhapura road, Habarana 50150',
  phone: '+94 75 699 8998',
  whatsapp: '+94 75 699 8998',
  email: 'reservations@tantorresort.com',
  mapsUrl: 'https://maps.app.goo.gl/tsm1zvaBTjxzfkUq8',
  checkInTime: '14:00',
  checkOutTime: '11:00',
  coordinates: {
    lat: 8.0451861,
    lng: 80.7281489,
  },
  amenities: [
    {
      title: 'Private jungle villas',
      description: 'secluded eco-villas tucked deep within Habarana\'s lush tropical forest.',
      icon: 'Trees',
    },
    {
      title: 'Natural plunge pools',
      description: 'refreshing private stone plunge pools immersed in natural jungle surroundings.',
      icon: 'Droplets',
    },
    {
      title: 'Guided elephant safaris',
      description: 'customized wildlife safaris to observe wild elephant herds in nearby sanctuaries.',
      icon: 'Binoculars',
    },
    {
      title: 'Wildlife at your doorstep',
      description: 'wake up to exotic birds, peacocks, and gentle jungle sounds right outside your balcony.',
      icon: 'Bird',
    },
    {
      title: 'Jungle infinity pool',
      description: 'swim right at the edge of the water with serene forest & canopy views.',
      icon: 'Waves',
    },
    {
      title: 'Sunset cocktail deck',
      description: 'handcrafted tropical elixirs served under evening jungle skies.',
      icon: 'Wine',
    },
  ],
  testimonials: [
    {
      quote:
        'We stayed at Tantor Resort Habarana for 2 nights, and it was an amazing experience from start to finish. The resort is peaceful, clean, and beautifully maintained. Our private pool with the cabana was fantastic—perfect for relaxing in complete privacy. Delicious food and exceptional hospitality!',
      author: 'Rumesh Dissanayaka',
      location: 'Google Review • Sri Lanka',
      rating: 5,
    },
    {
      quote:
        'We had an absolutely unforgettable stay at Tantor Resort. We stayed in the large treehouse accommodation, which was incredibly spacious, beautifully designed, and offered a unique, luxurious experience surrounded by nature. A special shoutout to Anu, who took amazing care of us!',
      author: 'Bernhard Rieder',
      location: 'Google Review • Austria',
      rating: 5,
    },
    {
      quote:
        'Our family of four spent six wonderful days at Tantor Resort. Tantor is a small, family-run resort with just four accommodation units, a swimming pool, and a beautifully kept garden. The staff were always smiling and kind. Anuu was an exceptional host who assisted us with local tips and excursions.',
      author: 'Søren Zahle',
      location: 'Google Review • Denmark',
      rating: 5,
    },
    {
      quote:
        'AMAZING! Our best stay in Sri Lanka. The room was really beautifully laid out, on stilts and in a tree. The lianas and branches of the trees hang everywhere, making you really feel like you are in a tree. Outdoor bathroom and wonderful staff. Highly recommended!',
      author: 'Rob Koopmans',
      location: 'Google Review • Netherlands',
      rating: 5,
    },
  ],
};
